- generic [active] [ref=e1]:
  - navigation [ref=e2]:
    - link "首页" [ref=e3] [cursor=pointer]:
      - /url: /
    - text: "|"
    - link "仪表盘" [ref=e4] [cursor=pointer]:
      - /url: /dashboard.html
    - text: "|"
    - link "DAG" [ref=e5] [cursor=pointer]:
      - /url: /dag.html
    - text: "|"
    - link "配置" [ref=e6] [cursor=pointer]:
      - /url: /config.html
  - main [ref=e7]:
    - generic [ref=e8]:
      - generic [ref=e9]:
        - heading "📈 仪表盘" [level=1] [ref=e10]
        - generic [ref=e11]:
          - button "天" [ref=e12] [cursor=pointer]
          - button "周" [ref=e13] [cursor=pointer]
          - button "月" [ref=e14] [cursor=pointer]
      - generic [ref=e15]:
        - generic [ref=e16]:
          - generic [ref=e17]: 总文章数
          - generic [ref=e18]: "100"
          - generic [ref=e19]: ↑ 100 本周期新增
        - generic [ref=e20]:
          - generic [ref=e21]: 周期费用
          - generic [ref=e22]: $0.07
          - generic [ref=e23]: "-"
        - generic [ref=e24]:
          - generic [ref=e25]: 日均采集
          - generic [ref=e26]: ~3
          - generic [ref=e27]: 近 30 天
        - generic [ref=e28]:
          - generic [ref=e29]: 活跃源
          - generic [ref=e30]: "2"
          - generic [ref=e31]: 个活跃数据源
      - generic [ref=e32]:
        - generic [ref=e33]:
          - heading "💰 成本趋势" [level=3] [ref=e34]
          - generic [ref=e37]:
            - generic [ref=e38]: 实际成本
            - generic [ref=e40]: 滚动均值
        - generic [ref=e42]:
          - heading "📊 来源分布" [level=3] [ref=e43]
          - generic [ref=e44]:
            - generic [ref=e46]:
              - generic [ref=e47]: rss
              - generic [ref=e48]: "71"
            - generic [ref=e52]:
              - generic [ref=e53]: github
              - generic [ref=e54]: "29"